### ISSUE TITLE
Missing models for RawNet

### ISSUE THREAD

**Issue by peter-lukac** [Jungjee/RawNet#10]
https://github.com/Jungjee/RawNet/blob/e767f178922fcfe78e412f58fbc50460e9118505/RawNet1/Keras/01-trn_RawNet.py#L19-L20

Hello.

I've been trying to trying to run the reproduction of the system from the original RawNet paper and found that these two modules are missing. Could you please upload them ?

**Comment by Jungjee** [comment]
Hi peter-lukac. Thanks for letting me know:)
I re-added the scripts plus a [model_bvec.py](https://github.com/Jungjee/RawNet/blob/master/RawNet1/Keras/model_bvec.py)
