### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by shankar0206** [Jungjee/RawNet#12]
It would of great help if you can provide the config yaml file that you used to train the pytorch model?

**Comment by Jungjee** [comment]
You can refer to [parser.py](../blob/master/parser.py). 
If you're talking about system configuration, there's one in "Environment settings"

Or is there something else you want to know?

**Comment by shankar0206** [comment]
Got it... i did not think about parser.py... that is all i wanted... also the code loads the optimizer state dict. Is that provided? If not can you upload it?

**Comment by Jungjee** [comment]
Sorry, as of now, I don't have plans to upload optimizer state dictionary :( 
Although, for the next update, I will include optimizer's state dictionary as well!

**Comment by shankar0206** [comment]
Cool. Thank you!!!
