### ISSUE TITLE
About the pretrained model

### ISSUE THREAD

**Issue by taylorlu** [Jungjee/RawNet#13]
Hi, when I test the model by using pretrained model `rawnet2_best_weights.pt`, it throws an error
` in Missing key(s) in state_dict: "block0.0.frm.fc.weight", "block0.0.frm.fc.bias", "block1.0.frm.fc.weight", "block1.0.frm.fc.bias", "block2.0.frm.fc.weight", "block2.0.frm.fc.bias", "block3.0.frm.fc.weight", "block3.0.frm.fc.bias", "block4.0.frm.fc.weight", "block4.0.frm.fc.bias", "block5.0.frm.fc.weight", "block5.0.frm.fc.bias`
It seems really missing these parameters after I checked the model by Netron.
Many thanks for your reply in advance.

**Comment by Jungjee** [comment]
Hello, have you tried loading on this file? 
[model_RawNet2_original_code.py](../blob/master/Pre-trained_model/model_RawNet2_original_code.py)

**Comment by taylorlu** [comment]
OK, it's my mistake, the original code is alll right.
