### ISSUE TITLE
script generate embedding

### ISSUE THREAD

**Issue by kewin1807** [Jungjee/RawNet#14]
pls provide me a script to get embedding audio. Thanks

**Comment by Jungjee** [comment]
Hi, for speaker embedding extraction, please refer to the below function 
[time_augmented_evaluate_model](../blob/master/trainer.py#L30) in [trainer.py](../blob/master/trainer.py). 
[line 41](../blob/master/trainer.py#L41) is the speaker embedding.

Thanks.
