### ISSUE TITLE
The generalization abality

### ISSUE THREAD

**Issue by ABexit** [Jungjee/RawNet#15]
The generalization of RawNet2 is poor?
I trained RawNet2 in AISHELL dataset with 340 speaker and tested in trail.txt with 8w pairs bulit by another 40 speaker of AISHELL, and the final eer is 3.46%. But when tested in 40 speaker of VCTK dataset with 8w pairs, the eer got 32.71%. Do you know why? Thanks.

**Comment by Jungjee** [comment]
Hi, it's not easy for me to judge the extent of generalization. 
I don't know how much difference AISHELL and VCTK datasets have. 
However, normally, I would not expect EER to increase over 30%. 
One example would be cross lingual experiments (train: English, test: Korean) which is not published. 
In this case, EER was somewhere between 5~7%. 

Hope this helps :)
