### ISSUE TITLE
How make embedding for single wave file?

### ISSUE THREAD

**Issue by paklau99988** [Jungjee/RawNet#16]
Is have function? No use batches or data loader, just one wav.

**Comment by Jungjee** [comment]
Hi, 
I didn't understand your question.. 
Could you provide more details?

**Comment by paklau99988** [comment]
I have a singls wav file beling to single speaker. Want extrcat embedding.

**Comment by Jungjee** [comment]
you can simply load the model, input one utterance with `unsqueeze(0)` to make batch size to 1
