### ISSUE TITLE
What is the requirement in terms of hardware?

### ISSUE THREAD

**Issue by underdogliu** [Jungjee/RawNet#19]
First of all thanks for such amazing work of RawNet and its variants!

I just want to know about the hardware requirements for training RawNet2 and modified RawNet2. I have following two questions:
1. I tried to run it with a single GPU with 12GB memory and failed. What was your experimental hardware setting?
2. Is it recommended to reduce number of mini batches for better memory handling?

**Comment by Jungjee** [comment]
Hi, 

1. I recall using 4 Nvidia Titan V GPUs.
2. You can reduce the size of mini-batch, however, it would take a lot of time to train VoxCeleb2 using a single GPU 
(regardless of your GPU generation, normally many recent systems take days using 4 GPUs )

My quick advice is to train the model using the train data of VoxCeleb1 and evaluate using VoxCeleb1 testset.
