### ISSUE TITLE
The link for Pre-trained weight parameters for Rawnet 3 is not available. 

### ISSUE THREAD

**Issue by Voicecon** [Jungjee/RawNet#27]
Hi there, 
I tried to download the pre-trained weight parameters from the provided link (https://huggingface.co/jungjee/RawNet3 ), but it seems like this link is invalid. I would appreciate if I get a correct link to download the pre-trained weights.

**Comment by Jungjee** [comment]
Hi, @Voicecon.

Did you try `git submodule update --init --recursive` as written in the readme file?
I tried again and it works for me.

Would you mind re-trying once and let me know?

**Comment by Voicecon** [comment]
@Jungjee  Now the link is working. Thanks so much for a quick reply.
