### ISSUE TITLE
Error in PreEmphasis Class

### ISSUE THREAD

**Issue by Divya1612** [Jungjee/RawNet#29]
I am getting the following error in the PreEmphasis class:

RawNet3/RawNetBasicBlock.py", line 20, in forward
    len(input.size()) == 2
AttributeError: 'builtin_function_or_method' object has no attribute 'size'

Could you please help?

**Comment by Jungjee** [comment]
Hi, can you print your `input`? such as type, value? 
Seems like your `input` is not a `torch.Tensor`.

**Comment by Divya1612** [comment]
Thanks! It has been resolved now.
