### ISSUE TITLE
Can I feed the 22050 sr wav to the pre-trained rawnet3 model ?

### ISSUE THREAD

**Issue by predawnang** [Jungjee/RawNet#31]
Hi
    I want to use rawnet3 model in my project to compute the speaker similarity of a pair of wavs. All the audio in my dataset is 22050Hz, for some reason I could down sample those audio to 16000 kHz. I wonder if the pretrained model is suitable to the 22050Hz audio.
Thanks

**Comment by Jungjee** [comment]
Hi @predawnang, yes I believe RawNet3 should work on downsampled 16 kHz waveforms. 
First downsample your waveforms to 16 kHz and then feed them to the model.

**Comment by predawnang** [comment]
Dear author, can I directly feed the 22khz wavforms to the model, will it cause performance decrease of the model?

**Comment by Jungjee** [comment]
I haven't tested that case, but it would be likely that the  output representations aren't representative.

In short, I recommend you not to.
