### ISSUE TITLE
Pytorch scripts?

### ISSUE THREAD

**Issue by Joepetey** [Jungjee/RawNet#4]
Any timeline on when the scripts will be uploaded?

Thank you!

**Comment by Jungjee** [comment]
Planning to upload before November since I have been working on another project.. Thank you for the interest:).

**Comment by Joepetey** [comment]
Ok, thank you!

I am eagerly awaiting your upload.

**Comment by Jungjee** [comment]
Update of baseline complete :) 
Now closing this issue.
