### ISSUE TITLE
Directory tree of files

### ISSUE THREAD

**Issue by ChenJiaDong9219** [Jungjee/RawNet#5]
Can you please in the readme show the directory tree of VoxCeleb1 files that were used in your experiment? I'm a bit confused when looking at 00-pre_process_waveforms.py.

**Comment by Jungjee** [comment]
Hi, if you could tell me which part you are confused it would be easier for me to help you :).
I will also show the directory tree of VoxCeleb1 that I have in meanwhile.

**Comment by ChenJiaDong9219** [comment]
@Jungjee any part that involves directory operation. if you can provide the directory tree, then the meaning of the code would be apparent.

**Comment by Jungjee** [comment]
Ok! I add a part of directory tree in 'keras/directory_tree.txt'.
Hope it helps. Below is a copy of the text file :)


=====
A directory tree of VoxCeleb1 dataset to help understanding 00-pre_process_waveforms.py

e.g. /DB/VoxCeleb1/voxceleb1_wav/A.J._Buckley/1zcIwhmdeo4_0000001.wav

+---A.J._Buckley
|       1zcIwhmdeo4_0000001.wav
|       1zcIwhmdeo4_0000002.wav
|       1zcIwhmdeo4_0000003.wav
|       7gWzIy6yIIk_0000001.wav
|       7gWzIy6yIIk_0000002.wav
|       ...
+---A.R._Rahman
|       0_laIeN-Q44_0000001.wav
|       6WO410QOeuo_0000001.wav
|       6WO410QOeuo_0000002.wav
|       6WO410QOeuo_0000003.wav
|       6WO410QOeuo_0000004.wav
|       6WO410QOeuo_0000005.wav
|       6WO410QOeuo_0000006.wav
|       
+---Aamir_Khan
|       5ablueV_1tw_0000001.wav
|       5ablueV_1tw_0000002.wav
|       5ablueV_1tw_0000003.wav
|       5ablueV_1tw_0000004.wav
