### ISSUE TITLE
RawNet2 PyTorch weights & inference

### ISSUE THREAD

**Issue by max810** [Jungjee/RawNet#6]
I have a couple of questions regarding RawNet2 usage for inference:
1) By "pre-trained model" in README you meant a model fully trained on VoxCeleb2? Or just the model after the pre-training phase on speaker identification task?
2) There are two implementations of RawNet2 - one in `model_RawNet2.py` file, one in `model_RawNet2_original_code.py`. The "pre-trained model"'s weights are for the latter. What are the differences between them and which one should I use for inference (on other datasets, not necesserily VoxCeleb1)
3) Are you planning on releasing the weights of the model fully trained on VoxCeleb2? I would like to experiment with it on other datasets, but, unfortunatel, don't have the ability to train it myself.

**Comment by Jungjee** [comment]
Hi, 

1. I meant the latter, fully trained on VoxCeleb2. 

2. There is no difference actually, it's just me doing some code refactoring for upload. 
In other words, the former is refactored for others to train with it, and the latter is the code I ran for experiments. 

3. As I mentioned in 1., at this stage, I'm not sure when I'm going to upload the trained weights using the refactored code.

Hope this helps :)
