### ISSUE TITLE
Missing .txt trial files

### ISSUE THREAD

**Issue by Zaylar** [Jungjee/RawNet#9]
Hi, I would like to use your rawNet code for training and am testing it out on the voxCeleb dataset first. However, for VoxCeleb1 I do not see the veri_test.txt file. For VoxCeleb2, I only see list_test_all_cleaned.txt and list_test_hard_cleaned.txt instead of the 6 txt files in the filetree. 

Could I check if this is supposed to be the case or are there missing files?

**Comment by Jungjee** [comment]
Hi, you can download the trial files [Here](http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox2.html)
